apiVersion: v1
kind: Secret
metadata:
  name: backup-storage-creds
  namespace: cnpg
type: Opaque
data:
  # AWS S3 credentials (base64 encoded)
  # Replace these with your actual AWS credentials
  ACCESS_KEY_ID: "your-base64-encoded-access-key"
  SECRET_ACCESS_KEY: "your-base64-encoded-secret-key"
---

# This is a placeholder for backup storage configuration
# The actual AWS S3 configuration is in cluster.yaml under backup section
