apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: default
spec:
  instances: 3
  storage:
    size: 1Gi
  # Backup configuration - AWS S3
  backup:
    barmanObjectStore:
      # Replace with your actual S3 bucket name
      destinationPath: "s3://cnpg-backup-510"
      s3Credentials:
        accessKeyId:
          name: backup-storage-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-storage-creds
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
